[brew]
ack = ""
aspell = ""
awscli = ""
broot = ""
colordiff = ""
colortail = ""
curl = ""
dmg2img = ""
dockutil = ""
duti = ""
exa = ""
exiftool = ""
faac = ""
faad2 = ""
fd = ""
fdupes = ""
ffmpeg = ""
findutils = ""
flac = ""
fzf = ""
gawk = ""
ghostscript = ""
git = ""
git-delta = ""
git-extras = ""
gnu-sed = ""
gnu-tar = ""
gpg = ""
graphviz = ""
grc = ""
grep = ""
"gromgit/fuse/ntfs-3g-mac" = ""
htop = ""
id3v2 = ""
imagemagick = ""
jnettop = ""
jq = ""
lame = ""
legit = ""
mozjpeg = ""
neovim = ""
openjdk = ""
openssh = ""
openssl = ""
optipng = ""
osxutils = ""
p7zip = ""
pandoc = ""
pdftk-java = ""
pinentry-mac = ""
pngcrush = ""
prettyping = ""
pstree = ""
pv = ""
python = ""
rclone = ""
recode = ""
rename = ""
ripgrep = ""
rmlint = ""
shellcheck = ""
shntool = ""
"smudge/smudge/nightlight" = ""
spoof-mac = ""
ssh-copy-id = ""
tccutil = ""
testdisk = ""
tldr = ""
tree = ""
unar = ""
uutils-coreutils = ""
watch = ""
webkit2png = ""
wget = ""
x264 = ""
xh = ""
yt-dlp = ""
zsh = ""

[cask]
adguard = ""
adguard-vpn = ""
aerial = ""
altserver = ""
amethyst = ""
balenaetcher = ""
blockblock = ""
dangerzone = ""
db-browser-for-sqlite = ""
disk-arbitrator = ""
disk-drill = ""
dupeguru = ""
electrum = ""
fork = ""
gimp = ""
"homebrew/cask-drivers/caldigit-thunderbolt-charging" = ""
"homebrew/cask-drivers/ftdi-vcp-driver" = ""
"homebrew/cask-drivers/logitech-options" = ""
"homebrew/cask-drivers/samsung-portable-ssd-t5" = ""
"homebrew/cask-fonts/font-sauce-code-pro-nerd-font" = ""
iina = ""
kap = ""
knockknock = ""
libreoffice = ""
little-snitch = ""
lulu = ""
macfuse= ""
mactex = ""
monitorcontrol = ""
musicbrainz-picard = ""
netnewswire = ""
pdf-images = ""
signal = ""
stats = ""
subsurface = ""
tor-browser = ""
transmission = ""
visual-studio-code = ""
xbar = ""
# QuickLooks plugins
# Source: https://github.com/sindresorhus/quick-look-plugins
apparency = ""
epubquicklook = ""
qlcolorcode = ""
qlimagesize = ""
qlmarkdown = ""
qlstephen = ""
qlvideo = ""
quicklook-json = ""
suspicious-package = ""

[mas]
"409183694" = ""  # Numbers
"409203825" = ""  # Keynotes
"1333542190" = "" # 1Password
"1408727408" = "" # WiFi Explorer Lite
"1176895641" = "" # Spark - Email App by Readdle
"1295203466" = "" # Microsoft Remote Desktop

[pip]
arrow = ""
black = ""
boltons = ""
bump2version = ""
check-wheel-contents = ""
"coverage[toml]" = ""
ipython-autotime = ""
isort = ""
jupyterlab = ""
jupyterlab-code-formatter = ""
matplotlib = ""
meta-package-manager = ""
neovim = ""
numpy = ""
pandas = ""
pgcli = ""
"pipdeptree[graphviz]" = ""
poetry = ""
pycodestyle = ""
pydocstyle = ""
pygments = ""
pylint = ""
pytest = ""
pytest-cov = ""
pytest-randomly = ""
pytest-sugar = ""
setuptools = ""
twine = ""

[vscode]
executablebookproject.myst-highlight = ""
ms-python.python = ""
ms-python.vscode-pylance = ""
ms-toolsai.jupyter = ""
ms-toolsai.jupyter-keymap = ""
samuelcolvin.jinjahtml = ""
tamasfe.even-better-toml = ""
trond-snekvik.simple-rst = ""
